# Generated by Django 4.2.4 on 2023-09-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myaap', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcedemicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('engineering', 'Engineering'), ('mechincal', 'Mechincal'), ('electrical', 'Electrical'), ('arts', 'Arts'), ('commerce', 'Commerce')], default='engineering', max_length=20)),
                ('batch', models.CharField(max_length=255)),
                ('enroll_rate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myaap.student')),
            ],
        ),
    ]
